# Modeling 

In [13]:
from sklearn import model_selection, preprocessing, linear_model, naive_bayes, metrics, svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.dummy import DummyClassifier
from sklearn import decomposition, ensemble
import pandas as pd

In [2]:
# load in dataframe
df = pd.read_csv('csv_files/9_1_all_books_df.csv')

In [3]:
# look at dataframe
print(df.columns)
print(df.shape)
df.head()

Index(['author', 'description', 'format', 'genre', 'month', 'pages',
       'publisher', 'rating', 'title', 'year', 'best_seller'],
      dtype='object')
(1373, 11)


author                                        description  \
0           Liane Moriarty  Six responsible adults. Three cute kids. One s...   
1           Bryn Greenwood  As the daughter of a meth dealer, Wavy knows n...   
2               Emma Cline  Northern California, during the violent end of...   
3  Cynthia D'Aprix Sweeney  <i>A warm, funny and acutely perceptive debut ...   
4             Jodi Picoult  Ruth Jefferson is a labor and delivery nurse a...   

      format    genre    month  pages           publisher  rating  \
0  Hardcover  Fiction     July    415      Flatiron Books    3.56   
1  Hardcover  Fiction   August    346  Thomas Dunne Books    4.07   
2  Hardcover  Fiction     June    355        Random House    3.47   
3  Hardcover  Fiction    March    368                Ecco    3.42   
4  Hardcover  Fiction  October    480    Ballantine Books    4.35   

                               title    year  best_seller  
0                 Truly Madly Guilty  2016.0            0  
1  All the Ugly and Wonderful Things  2016.0            0  
2                          The Girls  2016.0            0  
3                           The Nest  2016.0            0  
4                 Small Great Things  2016.0            0

In [16]:
# split the dataset into training and validation datasets 
X_train, X_test, y_train, y_test = model_selection.train_test_split(df_baseline[['rating', 'pages']], 
                                                                    df_baseline['best_seller'], 
                                                                    test_size = .2)

In [17]:
# this just includes pages and ratings along with the target of best seller or not
df_baseline = df[['rating', 'pages', 'best_seller']]

In [18]:
df_baseline.tail()

rating  pages  best_seller
1368    4.18    544            1
1369    3.94    383            1
1370    3.45    256            1
1371    4.05    480            1
1372    3.82    400            1

## Baseline model
- On numerical data only

In [28]:
base = DummyClassifier(random_state=42)

In [29]:
base.fit(X_train, y_train)

DummyClassifier(constant=None, random_state=42, strategy='stratified')

In [30]:
print('mean training accuracy' ,base.score(X_train, y_train))
print('mean test accuracy', base.score(X_test, y_test))

mean training accuracy 0.6675774134790529
mean test accuracy 0.6545454545454545


# Random Forest

In [12]:
random_forest = RandomForestClassifier()

In [31]:
random_forest.fit(X_train, y_train)

/Users/rhillery/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [34]:
random_forest.score(X_test, y_test)

0.7672727272727272

In [36]:
random_forest.decision_path(X_train)

(<1098x4544 sparse matrix of type '<class 'numpy.int64'>'
 	with 136282 stored elements in Compressed Sparse Row format>,
 array([   0,  489,  972, 1453, 1926, 2389, 2852, 3285, 3658, 4095, 4544]))

In [37]:
random_forest.decision_path(X_test)

(<275x4544 sparse matrix of type '<class 'numpy.int64'>'
 	with 34223 stored elements in Compressed Sparse Row format>,
 array([   0,  489,  972, 1453, 1926, 2389, 2852, 3285, 3658, 4095, 4544]))

In [38]:
random_forest.feature_importances_

array([0.49541055, 0.50458945])